name: Publish Extension
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: functions/yarn.lock

      - name: Cache functions NPM packages
        uses: actions/cache@v3
        with:
          path: functions/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install global NPM tools
        run: |
          yarn global add firebase-tools@latest
          firebase --version

      # The variable `FIREBASE_SA` must be a base64 encoded string
      # of the service account JSON to avoid problems with quote escaping and
      # conversion of '\n' characters generating invalid JSON
      - name: Set service account for Firebase CLI
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service_account.json" >> $GITHUB_ENV
          echo ${{ secrets.FIREBASE_SA }} | base64 -d -i - > service_account.json

      - run: firebase login:list

      - run: yarn --cwd functions install

      - run: yarn --cwd functions build

      - run: firebase ext:dev:publish --force oddbit/firebase-alerts            

      # Try to save potential log files if something went wrong
      - name: Upload debug log
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: debug-log-functions
          path: firebase-debug.log
          if-no-files-found: ignore
